---
openapi: 3.0.1
info:
  title: Products Http API
  description: Products Http API (Task 3 Serverless)
  contact:
    name: Yevheniy Gandzyuck
    email: e.barbedwire@gmail.com
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/bwire/T3-serverless/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://k7id9o1czl.execute-api.eu-west-1.amazonaws.com
tags:
- name: Products
  description: Products api (v1)
paths:
  /products:
    get:
      tags:
      - Products
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
  /products/{productId}:
    get:
      tags:
      - Products
      parameters:
      - name: productId
        in: path
        description: product identificator
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        "404":
          description: Product not found
components:
  schemas:
    Product:
      required:
      - description
      - id
      - price
      - title
      type: object
      properties:
        id:
          type: string
          example: 7567ec4b-b10c-48c5-9345-fc73c48a80a2
        price:
          type: number
          example: 100
        description:
          type: string
          example: This book is interesting to read
        title:
          type: string
          example: Refactoring by M. Fowler
